import type { BaseTool, ToolContext, ToolResult } from "./BaseTool.js";
import { getDb } from "../db/index.js";
import { id } from "../utils/ids.js";
import { nowIso } from "../utils/time.js";

export class InvoiceTool implements BaseTool {
  name = "invoice_tool";
  riskLevel = "low" as const;

  async execute(input: Record<string, unknown>, context: ToolContext): Promise<ToolResult> {
    const clientName = String(input.client_name ?? "Client");
    const items = Array.isArray(input.line_items)
      ? (input.line_items as Array<{ description: string; qty: number; unit_price: number }>)
      : [{ description: String(input.description ?? "Services rendered"), qty: 1, unit_price: Number(input.amount ?? 0) }];
    const notes = String(input.notes ?? "");
    const dueDate = String(input.due_date ?? addDays(30));

    const db = getDb();
    const company = db.prepare("SELECT name FROM companies WHERE id = ?").get(context.companyId) as { name: string } | undefined;
    const invoiceNumber = `INV-${Date.now().toString(36).toUpperCase()}`;

    const subtotal = items.reduce((sum, item) => sum + item.qty * item.unit_price, 0);
    const tax = subtotal * 0.1;
    const total = subtotal + tax;

    const content = renderInvoice({
      invoiceNumber,
      company: company?.name ?? "Your Company",
      clientName,
      items,
      subtotal,
      tax,
      total,
      dueDate,
      notes
    });

    const wpId = id("wp");
    db.prepare("INSERT INTO work_products (id, company_id, run_id, agent_id, type, title, content, created_at) VALUES (?, ?, ?, ?, 'invoice', ?, ?, ?)").run(wpId, context.companyId, context.runId ?? null, context.agentId ?? null, `Invoice ${invoiceNumber} — ${clientName}`, content, nowIso());

    return {
      output: { invoiceNumber, total: total.toFixed(2), dueDate, workProductId: wpId },
      workProductId: wpId
    };
  }
}

function addDays(days: number) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

function renderInvoice(data: { invoiceNumber: string; company: string; clientName: string; items: Array<{ description: string; qty: number; unit_price: number }>; subtotal: number; tax: number; total: number; dueDate: string; notes: string }) {
  const rows = data.items.map((item) => `| ${item.description} | ${item.qty} | $${item.unit_price.toFixed(2)} | $${(item.qty * item.unit_price).toFixed(2)} |`).join("\n");
  return `# Invoice ${data.invoiceNumber}

**From:** ${data.company}
**To:** ${data.clientName}
**Date:** ${new Date().toISOString().slice(0, 10)}
**Due:** ${data.dueDate}

---

## Line Items

| Description | Qty | Unit Price | Amount |
|---|---|---|---|
${rows}

---

**Subtotal:** $${data.subtotal.toFixed(2)}
**Tax (10%):** $${data.tax.toFixed(2)}
**Total Due:** $${data.total.toFixed(2)}

${data.notes ? `**Notes:** ${data.notes}` : ""}

---
*This invoice was generated by AI Company OS.*`;
}
