import { ResourcePage } from "./ResourcePage";
export function ProjectsPage({ companyId }: { companyId: string }) {
  return <ResourcePage companyId={companyId} resource="projects" title="Projects" description="Plan, assign, and track projects generated by humans or the CEO Agent." columns={["title", "status", "owner_agent_id", "goal_id", "created_at"]} fields={[{ key: "company_id", label: "Company ID" }, { key: "goal_id", label: "Goal" }, { key: "title", label: "Title" }, { key: "description", label: "Description", type: "textarea" }, { key: "status", label: "Status", default: "planning" }, { key: "owner_agent_id", label: "Owner Agent" }]} />;
}
