import { useMemo, useState } from "react";
import { FileText } from "lucide-react";
import { list } from "../api/client";
import { useApi } from "../hooks/useApi";
import { Badge } from "../components/ui/Badge";
import { Card } from "../components/ui/Card";
import { PageHeader } from "../components/layout/PageHeader";

export function WorkProductsPage({ companyId }: { companyId: string }) {
  const { data } = useApi(async () => {
    const [products, agents, tasks] = await Promise.all([list<any>("work-products"), list<any>("agents"), list<any>("tasks")]);
    return { products: products.filter((item) => item.company_id === companyId), agents, tasks };
  }, [companyId]);
  const [type, setType] = useState("all");
  const [selectedId, setSelectedId] = useState("");
  const products = useMemo(() => (data?.products ?? []).filter((item) => type === "all" || item.type === type), [data?.products, type]);
  const selected = products.find((item) => item.id === selectedId) ?? products[0];
  const types = Array.from(new Set((data?.products ?? []).map((item) => item.type || "note")));
  const agentName = (id?: string) => data?.agents.find((agent) => agent.id === id)?.name ?? "Unknown agent";
  const taskTitle = (id?: string) => data?.tasks.find((task) => task.id === id)?.title ?? "No linked task";
  return (
    <div>
      <PageHeader title="Work Products" description="Preview markdown, text outputs, drafts, reports, and run artifacts generated by agents." />
      <div className="mb-4 flex flex-wrap gap-2"><button className={`rounded-md border px-3 py-2 text-sm ${type === "all" ? "border-sky-300 bg-sky-300 text-slate-950" : "border-line bg-panel text-slate-300"}`} onClick={() => setType("all")}>All</button>{types.map((item) => <button key={item} className={`rounded-md border px-3 py-2 text-sm ${type === item ? "border-sky-300 bg-sky-300 text-slate-950" : "border-line bg-panel text-slate-300"}`} onClick={() => setType(item)}>{item}</button>)}</div>
      <div className="grid gap-4 lg:grid-cols-[360px_1fr]">
        <Card>{products.length ? <div className="grid gap-2">{products.map((product) => <button key={product.id} className={`rounded-md border p-3 text-left ${selected?.id === product.id ? "border-sky-300 bg-sky-950/40" : "border-line bg-slate-950"}`} onClick={() => setSelectedId(product.id)}><div className="flex items-center justify-between gap-2"><span className="font-medium">{product.title || product.type}</span><Badge>{product.type || "note"}</Badge></div><p className="mt-1 line-clamp-2 text-sm text-slate-400">{product.content || product.file_path || "Empty artifact"}</p></button>)}</div> : <p className="text-sm text-slate-400">No work products yet. Run a generated task to produce the first tangible artifact.</p>}</Card>
        <Card>{selected ? <div><div className="mb-3 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-accent" /><h2 className="font-semibold">{selected.title || selected.type}</h2></div><button onClick={() => { const blob = new Blob([selected.content || ""], { type: "text/plain" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `${(selected.title || selected.type || "work-product").replace(/[^a-z0-9]/gi, "_")}.md`; a.click(); URL.revokeObjectURL(url); }} className="rounded-md border border-line bg-slate-900 px-3 py-1.5 text-xs text-slate-300 hover:bg-slate-800">Download</button></div><div className="mb-3 flex flex-wrap gap-2"><Badge>{selected.type || "note"}</Badge><Badge>{agentName(selected.agent_id)}</Badge><Badge>{taskTitle(selected.task_id)}</Badge><Badge>{selected.created_at}</Badge></div><pre className="max-h-[620px] overflow-auto whitespace-pre-wrap rounded-md border border-line bg-slate-950 p-4 text-sm leading-6 text-slate-200">{selected.content || selected.file_path || "No previewable text content."}</pre></div> : <p className="text-sm text-slate-400">Select a work product to preview it.</p>}</Card>
      </div>
    </div>
  );
}
